# Generated by Django 2.2.5 on 2021-04-22 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mywell.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='email')),
                ('phonenumber', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='last login')),
                ('role', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True)),
                ('Company_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(blank=True, max_length=200, null=True)),
                ('Location', models.TextField()),
                ('Bearing_of_hole', models.CharField(blank=True, max_length=200, null=True)),
                ('Collar_elevation', models.FloatField(verbose_name='Collar_elevation-float-m')),
                ('Date_of_start', models.DateTimeField(verbose_name='Date_of_start')),
                ('Type_of_core_barrel', models.CharField(blank=True, max_length=200, null=True)),
                ('Drilling_Agency', models.CharField(blank=True, max_length=200, null=True)),
                ('Co_ordinate_east', models.FloatField(verbose_name='co-ordinates-float-east')),
                ('Co_ordinate_north', models.FloatField(verbose_name='co-ordinates-float-north')),
                ('Drill_hole_no', models.CharField(blank=True, max_length=200, null=True)),
                ('Total_depth', models.IntegerField(verbose_name='Total_depth-meters')),
                ('Page_no', models.IntegerField(verbose_name='page_no')),
                ('Date_of_completion', models.DateTimeField(verbose_name='Date_of_completion')),
                ('Rig_type', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Depth_from', models.FloatField(verbose_name='Depth_from-float')),
                ('Depth_to', models.FloatField(verbose_name='Depth_to-float')),
                ('Ground_elevation', models.FloatField(verbose_name='Ground_elevation-float(m)')),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Litholog', models.ImageField(blank=True, upload_to=mywell.models.upload_location)),
                ('Structure_condition', models.TextField(default='null')),
                ('Size_of_core_piceses_lt_10', models.IntegerField(verbose_name='Size_of_core_piceses_lt_10')),
                ('Size_of_core_piceses_10_25', models.IntegerField(verbose_name='Size_of_core_piceses_10_25')),
                ('Size_of_core_piceses_25_75', models.IntegerField(verbose_name='Size_of_core_piceses_25_75')),
                ('Size_of_core_piceses_75_150', models.IntegerField(verbose_name='Size_of_core_piceses_75_150')),
                ('Size_of_core_piceses_gt_150', models.IntegerField(verbose_name='Size_of_core_piceses_gt_150')),
                ('Core_recovery_0_20', models.IntegerField(verbose_name='Core_recovery_0_20')),
                ('Core_recovery_20_40', models.IntegerField(verbose_name='Core_recovery_20_40')),
                ('Core_recovery_40_60', models.IntegerField(verbose_name='Core_recovery_40_60')),
                ('Core_recovery_60_80', models.IntegerField(verbose_name='Core_recovery_60_80')),
                ('Core_recovery_80_100', models.IntegerField(verbose_name='Core_recovery_80_100')),
                ('RQD_0_25', models.IntegerField(verbose_name='RQD_0_25')),
                ('RQD_25_50', models.IntegerField(verbose_name='RQD_25_50')),
                ('RQD_50_75', models.IntegerField(verbose_name='RQD_50_75')),
                ('RQD_75_100', models.IntegerField(verbose_name='RQD_75_100')),
                ('SPT_N_Value', models.CharField(blank=True, max_length=200, null=True)),
                ('Penetration_Rate', models.FloatField(verbose_name='Penetration_Rate(cm/min)')),
                ('Size_of_Hole', models.CharField(blank=True, max_length=200, null=True)),
                ('Casing', models.CharField(blank=True, max_length=200, null=True)),
                ('Drill_Water_Loss_Nill', models.CharField(blank=True, max_length=200, null=True)),
                ('Drill_Water_Loss_Partial', models.CharField(blank=True, max_length=200, null=True)),
                ('Drill_Water_Loss_complete', models.CharField(blank=True, max_length=200, null=True)),
                ('Permeability_K_value_Lugon', models.FloatField(verbose_name='Permeability_K_value_or_Lugon')),
                ('IS_classification', models.CharField(blank=True, max_length=200, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywell.project')),
            ],
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_Users', models.IntegerField(blank=True, null=True)),
                ('License_Start_Date', models.DateField(blank=True, null=True, verbose_name='License_Start_Date')),
                ('License_End_Date', models.DateField(blank=True, null=True, verbose_name='License_End_Date')),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='group')),
            ],
        ),
    ]
