# Generated by Django 2.2.5 on 2021-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Date_of_completion',
            field=models.DateField(verbose_name='Date_of_completion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Date_of_start',
            field=models.DateField(verbose_name='Date_of_start'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='Core_recovery_0_20',
            field=models.IntegerField(blank=True, null=True, verbose_name='Core_recovery_0_20'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='Core_recovery_20_40',
            field=models.IntegerField(blank=True, null=True, verbose_name='Core_recovery_20_40'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='Core_recovery_40_60',
            field=models.IntegerField(blank=True, null=True, verbose_name='Core_recovery_40_60'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='Core_recovery_60_80',
            field=models.IntegerField(blank=True, null=True, verbose_name='Core_recovery_60_80'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='Core_recovery_80_100',
            field=models.IntegerField(blank=True, null=True, verbose_name='Core_recovery_80_100'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='RQD_0_25',
            field=models.IntegerField(blank=True, null=True, verbose_name='RQD_0_25'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='RQD_25_50',
            field=models.IntegerField(blank=True, null=True, verbose_name='RQD_25_50'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='RQD_50_75',
            field=models.IntegerField(blank=True, null=True, verbose_name='RQD_50_75'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='RQD_75_100',
            field=models.IntegerField(blank=True, null=True, verbose_name='RQD_75_100'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='Size_of_core_piceses_10_25',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size_of_core_piceses_10_25'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='Size_of_core_piceses_25_75',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size_of_core_piceses_25_75'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='Size_of_core_piceses_75_150',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size_of_core_piceses_75_150'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='Size_of_core_piceses_gt_150',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size_of_core_piceses_gt_150'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='Size_of_core_piceses_lt_10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size_of_core_piceses_lt_10'),
        ),
    ]
